name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEFAULT_RUBY: 3.1

jobs:
  build:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        ruby:
        - 2.7
        - 3.1
        - 3.2

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: dtolnay/rust-toolchain@master
      with:
        toolchain: stable
    - name: Install dependencies
      run: bundle install
    - name: Print GLIBC
      run: echo $(ldd --version)
    - name: Build crate
      run: bundle exec rake build
    - name: Lint source code with with RuboCop
      if: ${{ matrix.ruby == env.DEFAULT_RUBY }}
      run: bundle exec rake rubocop
    - name: Verify static types with Steep
      if: ${{ matrix.ruby == env.DEFAULT_RUBY }}
      run: bundle exec rake steep
    - name: Transpile source source with RubyNext
      run: bundle exec rake nextify
    - name: Run specs with RSpec
      if: ${{ github.ref != 'refs/heads/main' }}
      run: bundle exec rake spec
