name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DEFAULT_RUBY: 3.1

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
        - 2.7
        - 3.1
        - 3.2

    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: 1.60.0
    - name: Install dependencies
      run: bundle install
    - name: Cache crate
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: cargo-${{ hashFiles('**/Cargo.lock') }}-ruby-${{ matrix.ruby }}
    - name: Build crate
      run: bundle exec rake build
    - name: Lint source code with with RuboCop
      if: ${{ matrix.ruby == env.DEFAULT_RUBY }}
      run: bundle exec rake rubocop
    - name: Verify static types with Steep
      if: ${{ matrix.ruby == env.DEFAULT_RUBY }}
      run: bundle exec rake steep
    - name: Transpile source source with RubyNext
      run: bundle exec rake nextify
    - name: Run specs with RSpec
      if: ${{ github.ref != 'refs/heads/main' }}
      run: bundle exec rake spec
